### ISSUE TITLE
Latest changes not merged 

### ISSUE THREAD

**Issue by acharyasaagar** [FreeCodeCampHelsinki/HELSynchers#5]
## Seems like the component files haven't been added yet 

When I try to serve the angular app with 
        ````    ng serve -o ```` 
it is throwing the components not found and in fact the components don't exist in the code yet.

**Comment by ponkape** [comment]
Does this problem still exists ?

**Comment by tikishabudin** [comment]
Don't forget to run "npm install" from the command line, after you clone this repo for the first time.
