### ISSUE TITLE
Vulnerabilities. How to fix 

### ISSUE THREAD

**Issue by ponkape** [FreeCodeCampHelsinki/HELSynchers#6]
How to handle these vulnerabilities? Is it just running audit fix or? While doing `ng serve --open` this message appears:

found 14 vulnerabilities (9 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by tikishabudin** [comment]
I think I got it fixed. Was an issue with one of the dependencies. I've updated the package.json file and it should have fixed the issue. So, go ahead and log into you github account select the repo and first cick "Compare" (top right side. Just above the clone button) then update your repo before doing a pull. That's if you forked it. If you didn't just clone the master
